#!/bin/bash

### PROMPT_COMMAND ###
__prompt_command() {
	# Store command return value (MUST be first line)
	local cmd_ret="$?"
	
	###############################
	### Set prompt return value ###
	###############################
	local cmd=( $(history 1) )
	local cmd_num=${cmd[0]}
	: ${PROMPT_LAST_CMD_NUM:=$cmd_num}
	if [ $PROMPT_LAST_CMD_NUM -ne $cmd_num -a $cmd_ret -ne 0 ]; then
		PS1_RETURN=$cmd_ret
	else
		PS1_RETURN=
	fi
	PROMPT_LAST_CMD_NUM=$cmd_num
	
	##########################
	### Check UID for root ###
	##########################
	if [ $EUID -eq 0 ]; then
		PS1_ROOT=1
	else
		PS1_ROOT=
	fi
	
	########################
	### VCS Branch Names ###
	########################
	local branch
	
	VCS_BRANCH=
	VCS_BRANCH_SHORT=
	VCS_BRANCH_LONG=
	
	# Git branches
	if hash __git_ps1 2>/dev/null; then
		branch=$(__git_ps1 "(%s)")
		[ -n "$branch" ] && VCS_BRANCH="$branch"
	fi
	
	# SVN branches
	# https://github.com/mcandre/svn-prompt
	if hash parse_svn_branch 2>/dev/null; then
		branch=$(parse_svn_branch)
		[ -n "$branch" ] && VCS_BRANCH="$branch"
	fi
	
	# Long/short branch name (for multiline prompt)
	if [ "${#VCS_BRANCH}" -gt "25" ]; then
		VCS_BRANCH_LONG="$VCS_BRANCH"
	elif [ -n "$VCS_BRANCH" ]; then
		VCS_BRANCH_SHORT="$VCS_BRANCH"
	fi
	
	export ${!VCS_*}
}
PROMPT_COMMAND="__prompt_command;$PROMPT_COMMAND"
### PROMPT_COMMAND ###

__set_ps1() {
	# Define colors for the prompt
	# (S=Bold/Strong,D=Dark,I=Italic,U=Underline,BG=Background)
	# (R=Red G=Green B=Blue C=Cyan M=Magenta Y=Yellow K=Black W=White)
	local -r RES="\[\e[0m\]" # Reset to default
	local -r K="\[\e[30m\]" SK="\[\e[1;30m\]" # DK="\[\e[2;30m\]" IK="\[\e[3;30m\]" UK="\[\e[4;30m\]" BGK="\[\e[40m\]"
	local -r R="\[\e[31m\]" SR="\[\e[1;31m\]" # DR="\[\e[2;31m\]" IR="\[\e[3;31m\]" UR="\[\e[4;31m\]" BGR="\[\e[41m\]"
	local -r G="\[\e[32m\]" SG="\[\e[1;32m\]" # DG="\[\e[2;32m\]" IG="\[\e[3;32m\]" UG="\[\e[4;32m\]" BGG="\[\e[42m\]"
	local -r Y="\[\e[33m\]" SY="\[\e[1;33m\]" # DY="\[\e[2;33m\]" IY="\[\e[3;33m\]" UY="\[\e[4;33m\]" BGY="\[\e[43m\]"
	local -r B="\[\e[34m\]" SB="\[\e[1;34m\]" # DB="\[\e[2;34m\]" IB="\[\e[3;34m\]" UB="\[\e[4;34m\]" BGB="\[\e[44m\]"
	local -r M="\[\e[35m\]" SM="\[\e[1;35m\]" # DM="\[\e[2;35m\]" IM="\[\e[3;35m\]" UM="\[\e[4;35m\]" BGM="\[\e[45m\]"
	local -r C="\[\e[36m\]" SC="\[\e[1;36m\]" # DC="\[\e[2;36m\]" IC="\[\e[3;36m\]" UC="\[\e[4;36m\]" BGC="\[\e[46m\]"
	local -r W="\[\e[37m\]" SW="\[\e[1;37m\]" # DW="\[\e[2;37m\]" IW="\[\e[3;37m\]" UW="\[\e[4;37m\]" BGW="\[\e[47m\]"
	
	# Single line prompt
	# export PS1="${debian_chroot:+($debian_chroot)}$B\w \${VCS_BRANCH:+$R(\$VCS_BRANCH) }$SB\$$W "

	# Multiline for long branch names
	PS1="\${PS1_RETURN:+$Y\$PS1_RETURN$RES }"
	PS1+="\${VCS_BRANCH_LONG:+\n$R\$VCS_BRANCH$RES\n}"
	PS1+="${debian_chroot:+($debian_chroot) }"
	PS1+="${SSH_TTY:+$SR\h$RES:}"
	PS1+="$B\\w \${VCS_BRANCH_SHORT:+$R\$VCS_BRANCH }$SB\${PS1_ROOT:+$SR}\\\$$RES "
}

__set_ps1
