#!/bin/bash
# Just-in-time bash prompt
# Author: Daniel Matthies <mageluingil@gmail.com>
# Revised: 2023-10-01
# 
# ----Format----
# [exit-status ][[runtime]
# [project-name version]
# [long branch name (multiline)]
# ][(chroot) ][su-user@][ssh-host:]dir [short branch name ] $ 

declare PROMPT_HISTCONTROL PROMPT_LAST_CMD_NUM
declare -A PROMPT_PROJECT

__jit_prompt_command() {
	local cmd_ret="$?" # Save command exit status (MUST be first line)
	local cmd_end=$(date +%s)
	unset -v ${!PS1_*} # Remove all temporary PS1 customization variables
	
	# Disable history options (we need the full history)
	PROMPT_HISTCONTROL="${HISTCONTROL-$PROMPT_HISTCONTROL}"
	unset -v HISTCONTROL
	
	# Parse the last command from history
	local cmd_num cmd_start cmd_rest cmd
	read cmd_num cmd_start cmd_rest < <(HISTTIMEFORMAT='%s ;' history 1)
	IFS=';' read -r _ cmd <<<"$cmd_rest" # Preserve original whitespace and escapes
	
	###############################
	### Save prompt exit status ###
	###############################
	# Only show error exit status, only once per command, and never on the first line
	if [[ -n $PROMPT_LAST_CMD_NUM && $PROMPT_LAST_CMD_NUM != $cmd_num && $cmd_ret -ne 0 ]]; then
		PS1_RETURN="$cmd_ret"
	fi
	
	##############################
	### Command execution time ###
	##############################
	local time=$(($cmd_end - $cmd_start))
	if [[ $time -ge 10 && $PROMPT_LAST_CMD_NUM != $cmd_num ]]; then
		if (($time >= 3600)); then
			PS1_CMD_TIME="$(printf "%d:%02d:%02d" $(($time/3600)) $((($time%3600)/60)) $(($time%60)))"
		elif (($time >= 60)); then
			PS1_CMD_TIME="$(printf "%d:%02d\n" $(($time/60)) $(($time%60)))"
		else
			PS1_CMD_TIME="${time}s"
		fi
	fi
	
	################
	# Project Info #
	################
	
	if [[ "${PROMPT_PROJECT[dir]}" = "$PWD" && ! -N "${PROMPT_PROJECT[meta]}" ]]; then
		: # Only show project info on entering directory or if it's changed
	elif hash node 2>/dev/null && [[ -f "composer.json" || -f "package.json" ]]; then
		# For js-based (composer/npm) projects
		PROMPT_PROJECT[dir]="$PWD"
		[[ -f "composer.json" ]] && PROMPT_PROJECT[meta]="composer.json" || PROMPT_PROJECT[meta]="package.json"
		PS1_PROJECT_VERSION="$(node -p "p=require('./${PROMPT_PROJECT[meta]}');[p.name||'',p.version||''].filter(Boolean).join(' ');")"
		touch -a "${PROMPT_PROJECT[meta]}"
	else
		PROMPT_PROJECT=( ) # no project files found
	fi
	
	########################
	### VCS Branch Names ###
	########################
	# Git branches
	if [[ -z "$PS1_VCS_BRANCH" ]] && hash __git_ps1 2>/dev/null; then
		PS1_VCS_BRANCH=$(__git_ps1 "(%s)")
	fi
	
	# SVN branches (https://github.com/mcandre/svn-prompt)
	if [[ -z "$PS1_VCS_BRANCH" ]] && hash parse_svn_branch 2>/dev/null; then
		PS1_VCS_BRANCH=$(parse_svn_branch)
	fi
	
	# Long/short branch name (for multiline prompt)
	if ((${#PS1_VCS_BRANCH} > 25)); then
		PS1_VCS_BRANCH_LONG="$PS1_VCS_BRANCH"
	elif ((${#PS1_VCS_BRANCH} > 0)); then
		PS1_VCS_BRANCH_SHORT="$PS1_VCS_BRANCH"
	fi
	
	############################
	### Multiline Formatting ###
	############################
	[[ -n "$PS1_CMD_TIME" || -n "$PS1_VCS_BRANCH_LONG" || -n "$PS1_PROJECT_VERSION" ]] && PS1_BR1=$'\n'
	
	###############
	### Cleanup ###
	###############
	# Re-evaluate history with original HISTCONTROL value
	if [[ -n "$PROMPT_HISTCONTROL" ]]; then
		# A bug in bash 4.2 causes history -s to delete an extra history entry
		[[ $BASH_VERSION != 4.2* ]] && history -d $cmd_num
		HISTCONTROL="$PROMPT_HISTCONTROL" history -s "$cmd"
	fi
	
	# Save the last effective command number
	read PROMPT_LAST_CMD_NUM _ < <(history 1)
}
PROMPT_COMMAND="__jit_prompt_command;$PROMPT_COMMAND"

is_ssh() {
	# Check for SSH env vars
	[[ -n "$SSH_TTY" || -n "$SSH_CONNECTION" || -n "$SSH_CLIENT" ]] && return 0
	# Check for SSH parent process recursively
	local name ppid
	read name ppid < <(ps -o comm= -o ppid= -p ${1:-$PPID})
	[[ "$name" =~ sshd ]] && return 0
	(( $ppid <= 1 )) && return 1
	is_ssh $ppid
}

__set_ps1() {
	# Define colors (N = No style)
	local -r N="\[\e[0m\]" Y="\[\e[33m\]" B="\[\e[34m\]" M="\[\e[35m\]" C="\[\e[36m\]" SR="\[\e[1;31m\]" SG="\[\e[1;32m\]" SB="\[\e[1;34m\]"
	
	# Check if user is root
	((EUID == 0)) && local user_color="$SR"
	# Check if using su
	[[ "$(whoami)" != "$(stat -c '%U' "$(tty)")" ]] && local show_user=true
	# Check for SSH & color support
	is_ssh && local show_host=true
	if ( hash tput 2>/dev/null && (($(tput colors) >= 256)) ) || [[ $TERM = *256* ]]; then
		local host_color="${HOSTCOLOR:-\[\e[1;38;5;124m\]}"
	fi
	# Check for "pretty" hostname
	if hash hostnamectl 2>/dev/null; then
		local HOSTNAME="$(hostnamectl --pretty)"
	fi
	
	PS1="$N"
	PS1+="\${PS1_RETURN:+$Y\$PS1_RETURN$N }" # exit status (if non-zero)
	PS1+="\${PS1_CMD_TIME:+⌛\${PS1_CMD_TIME} }" # command runtime
	PS1+="\$PS1_BR1" # newline after long run times / before long branch names
	PS1+="\${PS1_PROJECT_VERSION:+$M[\$PS1_PROJECT_VERSION]\n$N}" # project name & version
	PS1+="\${PS1_VCS_BRANCH_LONG:+$C\$PS1_VCS_BRANCH$N\n}" # newline after long branch names
	PS1+="${debian_chroot:+($debian_chroot) }" # chroot stuff
	PS1+="${show_user:+${user_color:-$SG}\u$N@}" # username (if su)
	PS1+="${show_host:+${host_color:-$SR}${HOSTNAME:-\h}$N}" # hostname (if SSH)
	[[ -n "$show_user" || -n "$show_host" ]] && PS1+=":"
	PS1+="$B\\w \${PS1_VCS_BRANCH_SHORT:+$C\$PS1_VCS_BRANCH }${user_color:-$SB}\\\$$N " # dir [branch ]$ 
	export PS1 # export for sudo -E
}

__set_ps1
